name: neutron_example
description: An example program using Neutron
version: 0.1.0
homepage: https://github.com/ExpidusOS/neutron

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=2.11.0'

dependencies:
  flutter:
    sdk: flutter

  neutron:
    path: ../.

flutter:
  uses-material-design: true
