name: flutter_engine
description: Dart bindings for the embedded Flutter Engine
version: 0.1.0
homepage: https://github.com/flutter/engine

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  ffi: ^2.0.1
  ffigen: ^7.2.1
