name: neutron_shimmy
description: Shims API
version: 0.1.0
homepage: https://github.com/ExpidusOS/neutron

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  web_ffi: ^0.7.2
  neutron_elemental:
    path: ../elemental
  neutron_platform:
    path: ../platform

dev_dependencies:
  ffi: ^2.0.1
  ffigen: ^7.2.1
