name: neutron_elemental
description: Elemental is a simple type system similar to GObject but aims to be more portable.
version: 0.1.0
homepage: https://github.com/ExpidusOS/neutron

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  web_ffi: ^0.7.2

dev_dependencies:
  ffi: ^2.0.1
  ffigen: ^7.2.1
