name: neutron_elemental
description: Elemental is a simple type system similar to GObject but aims to be more portable.
version: 0.1.0
homepage: https://github.com/ExpidusOS/neutron

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  ffi: ^2.0.1
  ffigen: ^6.0.1

flutter:
  plugins:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
