name: neutron_displaykit
description: Display server API for compositors and clients for ExpidusOS's Neutron
version: 0.1.0
homepage: https://github.com/ExpidusOS/neutron

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  web_ffi: ^0.7.2
  neutron_elemental:
    path: ../elemental

dev_dependencies:
  ffi: ^2.0.1
  ffigen: ^7.2.1
